package com.unipro.test.framework;

import java.util.Map;

import com.google.common.collect.Table;

public class Globals {

	
	public static Map<String, Table<String, String, String>> excelSheetData;

	public static class Inventory {
		final public static String SHEETNAME = "Inventory";
		final public static String SHEETNAME1 = "Department";
		final public static String SHEETNAME2 = "Category";
		final public static String SHEETNAME3 = "GAcreate";
		final public static String SHEETNAME4 = "Subcategory";
		final public static String SHEETNAME5 = "Brand";
		final public static String SHEETNAME6 = "GRNcreate";
		final public static String SHEETNAME7 = "Floor";
		final public static String SHEETNAME8 = "Purchaseorder";
		final public static String SHEETNAME9 = "Class";
		final public static String SHEETNAME10 = "Subclass";
		final public static String SHEETNAME11 = "Itemtype";
		final public static String SHEETNAME12 = "Purchasereturn";
		final public static String SHEETNAME13 = "Tax";
		final public static String SHEETNAME14 = "Uom";
		final public static String SHEETNAME15 = "Section";
		final public static String SHEETNAME16 = "Bin";
		final public static String SHEETNAME17 = "PurchasereturnReq";
		final public static String SHEETNAME18 = "Shelf";
		final public static String SHEETNAME19 = "Warehouse";
		final public static String SHEETNAME20 = "Size";
		final public static String SHEETNAME21 = "Style";
		final public static String SHEETNAME22 = "Baseuom";
		final public static String SHEETNAME23 = "CreditDebitnote";
		final public static String SHEETNAME24 = "AddDed";
		final public static String SHEETNAME25 = "Zone";
		final public static String SHEETNAME26 = "PoVendorChange";
		final public static String SHEETNAME27 = "CompanySettings";
		final public static String SHEETNAME28 = "DisplayandContracts";
		final public static String SHEETNAME29 = "StockAdjustmentType";
		final public static String SHEETNAME30 = "Merchandise";
		final public static String SHEETNAME31 = "ConsolidatedPocreate";
		final public static String SHEETNAME32 = "PurchaseOrderStatus";
		final public static String SHEETNAME33 = "Manufacturer";
		final public static String SHEETNAME34 = "AutoPO";
		final public static String SHEETNAME35 = "Vendorcatelog";
		final public static String SHEETNAME36 = "ConsolidatedPO";
		final public static String SHEETNAME37 = "Inventorychange";
		final public static String SHEETNAME38 = "InventoryCostReset";
		final public static String SHEETNAME39 = "Inventorymovement";
		final public static String SHEETNAME40 = "Origion";
		final public static String SHEETNAME41 = "Transport";
		final public static String SHEETNAME42 = "Barcode";
		final public static String SHEETNAME43 = "InventoryHistory";
		final public static String SHEETNAME44 = "ReorderSettings";
		final public static String SHEETNAME45 = "InventoryParentChildSetting";
		final public static String SHEETNAME46 = "Distribution";
		final public static String SHEETNAME47 = "InventoryParameter";
		final public static String SHEETNAME48 = "PackageInventory";
		final public static String SHEETNAME49 = "RefillingScheduling";
		final public static String SHEETNAME50 = "LocationWisePriceChange";
		final public static String SHEETNAME51 = "PriceChangeBatchItem";
		final public static String SHEETNAME52 = "PriceChangeNonBatchItem";
		final public static String SHEETNAME53 = "PriceImportExport";
		final public static String SHEETNAME54 = "FreeItem";
		final public static String SHEETNAME55 = "NormalPromotion";
		final public static String SHEETNAME56 = "OtherPromotion";
		final public static String SHEETNAME57 = "DayBasedPromotion";
		final public static String SHEETNAME58 = "RevokePromotion";
		final public static String SHEETNAME59 = "Payments";
		final public static String SHEETNAME60 = "Creditinvoice";
		final public static String SHEETNAME61 = "CustomerReceipts";
		final public static String SHEETNAME62 = "Billcancel";
		final public static String SHEETNAME63 = "SalesTransaction";
		final public static String SHEETNAME64 = "StockAdjustment";
		final public static String SHEETNAME65 = "SalesOrder";
		final public static String SHEETNAME66 = "StockUpdate";
		
		public static Table<String, String, String> inventorySheetData;
		public static Table<String, String, String> DepartmentSheetData;
		public static Table<String, String, String> CategorySheetData;
		public static Table<String, String, String> GRNcreateSheetData;
		public static Table<String, String, String> GAcreateSheetData;
		public static Table<String, String, String> SubcategorySheetData;
		public static Table<String, String, String> BrandSheetData;
		public static Table<String, String, String> FloorSheetData;
		public static Table<String, String, String> PurchaseorderSheetData;
		public static Table<String, String, String> ClassSheetData;
		public static Table<String, String, String> SubclassSheetData;
		public static Table<String, String, String> ItemtypeSheetData;
		public static Table<String, String, String> PurchasereturnSheetData;
		public static Table<String, String, String> PurchasereturnReqSheetData;
		public static Table<String, String, String> TaxSheetData;
		public static Table<String, String, String> UomSheetData;
		public static Table<String, String, String> SectionSheetData;
		public static Table<String, String, String> BinSheetData;
		public static Table<String, String, String> ShelfSheetData;
		public static Table<String, String, String> WarehouseSheetData;
		public static Table<String, String, String> SizeSheetData;
		public static Table<String, String, String> StyleSheetData;
		public static Table<String, String, String> BaseuomSheetData;
		public static Table<String, String, String> CreditDebitnoteSheetData;
		public static Table<String, String, String> AddDedSheetData;
		public static Table<String, String, String> ZoneSheetData;
		public static Table<String, String, String> PoVendorChangeSheetData;
		public static Table<String, String, String> CompanySettingsSheetData;
		public static Table<String, String, String> DisplayandContractsSheetData;
		public static Table<String, String, String> StockAdjustmentTypeSheetData;
		public static Table<String, String, String> MerchandiseSheetData;
		public static Table<String, String, String> ConsolidatedPocreateSheetData;
		public static Table<String, String, String> PurchaseOrderStatusSheetData;
		public static Table<String, String, String> ManufacturerSheetData;
		public static Table<String, String, String> AutoPOSheetData;
		public static Table<String, String, String> VendorcatelogSheetData;
		public static Table<String, String, String> ConsolidatedPOSheetData;
		public static Table<String, String, String> InventorychangeSheetData;
		public static Table<String, String, String> InventoryCostResetSheetData;
		public static Table<String, String, String> InventorymovementSheetData;
		public static Table<String, String, String> OrigionSheetData;
		public static Table<String, String, String> TransportSheetData;
		public static Table<String, String, String> BarcodeSheetData;
		public static Table<String, String, String> InventoryHistorySheetData;
		public static Table<String, String, String> ReorderSettingsSheetData;
		public static Table<String, String, String> InventoryParentChildSettingSheetData;
		public static Table<String, String, String> DistributionSheetData;
		public static Table<String, String, String> InventoryParameterSheetData;
		public static Table<String, String, String> PackageinventorySheetData;
		public static Table<String, String, String> RefillingSchedulingSheetData;
		public static Table<String, String, String> LocationWisePriceChangeSheetData;
		public static Table<String, String, String> PriceChangeBatchItemSheetData;
		public static Table<String, String, String> PriceChangeNonBatchItemItemSheetData;
		public static Table<String, String, String> PriceImportExportSheetData;
		public static Table<String, String, String> FreeItemSheetData;
		public static Table<String, String, String> NormalPromotionSheetData;
		public static Table<String, String, String> OtherPromotionSheetData;
		public static Table<String, String, String> DayBasedPromotionSheetData;
		public static Table<String, String, String> RevokePromotionSheetData;
		public static Table<String, String, String> PaymentsSheetData;
		public static Table<String, String, String> CreditinvoiceSheetData;
		public static Table<String, String, String> CustomerReceiptsSheetData;
		public static Table<String, String, String> BillcancelSheetData;
		public static Table<String, String, String> SalesTransactionSheetData;
		public static Table<String, String, String> StockAdjustmentSheetData;
		public static Table<String, String, String> SalesOrderSheetData;
		public static Table<String, String, String> StockUpdateSheetData;
		
		
		public static Map<String, String> inventoryrowwiseData;
		public static Map<String, String> DepartmentrowwiseData;
		public static Map<String, String> CategoryrowwiseData;
		public static Map<String, String> GAcreaterowwiseData;
		public static Map<String, String> SubcategoryrowwiseData;
		public static Map<String, String> BrandrowwiseData;
		public static Map<String, String> GRNcreaterowwiseData;
		public static Map<String, String> FloorrowwiseData;
		public static Map<String, String> PurchaseorderrowwiseData;
		public static Map<String, String> ClassrowwiseData;
		public static Map<String, String> SubclassrowwiseData;
		public static Map<String, String> ItemtyperowwiseData;
		public static Map<String, String> PurchasereturnrowwiseData;
		public static Map<String, String> TaxrowwiseData;
		public static Map<String, String> UomrowwiseData;
		public static Map<String, String> SectionrowwiseData;
		public static Map<String, String> BinrowwiseData;
		public static Map<String, String> PurchasereturnReqrowwiseData;
		public static Map<String, String> ShelfrowwiseData;
		public static Map<String, String> WarehouserowwiseData;
		public static Map<String, String> SizerowwiseData;
		public static Map<String, String> StylerowwiseData;
		public static Map<String, String> BaseuomrowwiseData;
		public static Map<String, String> CreditDebitnoterowwiseData;
		public static Map<String, String> AddDedrowwiseData;
		public static Map<String, String> ZonerowwiseData;
		public static Map<String, String> PoVendorChangerowwiseData;
		public static Map<String, String> CompanySettingsrowwiseData;
		public static Map<String, String> DisplayandContractsrowwiseData;
		public static Map<String, String> StockAdjustmentTyperowwiseData;
		public static Map<String, String> MerchandiserowwiseData;
		public static Map<String, String> ConsolidatedPocreaterowwiseData;
		public static Map<String, String> PurchaseOrderStatusrowwiseData;
		public static Map<String, String> ManufacturerrowwiseData;
		public static Map<String, String> AutoPOrowwiseData;
		public static Map<String, String> VendorcatelogrowwiseData;
		public static Map<String, String> ConsolidatedPOrowwiseData;
		public static Map<String, String> InventorychangerowwiseData;
		public static Map<String, String> InventoryCostResetrowwiseData;
		public static Map<String, String> InventorymovementrowwiseData;
		public static Map<String, String> OrigionrowwiseData;
		public static Map<String, String> TransportrowwiseData;
		public static Map<String, String> BarcoderowwiseData;
		public static Map<String, String> InventoryHistoryrowwiseData;
		public static Map<String, String> ReorderSettingsrowwiseData;
		public static Map<String, String> InventoryParentChildSettingrowwiseData;
		public static Map<String, String> DistributionrowwiseData;
		public static Map<String, String> InventoryParameterrowwiseData;
		public static Map<String, String> PackageinventoryrowwiseData;
		public static Map<String, String> RefillingSchedulingrowwiseData;
		public static Map<String, String> LocationWisePriceChangerowwiseData;
		public static Map<String, String> PriceChangeBatchItemrowwiseData;
		public static Map<String, String> PriceChangeNonBatchItemItemrowwiseData;
		public static Map<String, String> PriceImportExportrowwiseData;
		public static Map<String, String> FreeItemrowwiseData;
		public static Map<String, String> NormalPromotionrowwiseData;
		public static Map<String, String> OtherPromotionrowwiseData;
		public static Map<String, String> DayBasedPromotionrowwiseData;
		public static Map<String, String> RevokePromotionrowwiseData;
		public static Map<String, String> PaymentsrowwiseData;
		public static Map<String, String> CreditinvoicerowwiseData;
		public static Map<String, String> CustomerReceiptsrowwiseData;
		public static Map<String, String> BillcancelrowwiseData;
		public static Map<String, String> SalesTransactionrowwiseData;
		public static Map<String, String> StockAdjustmentrowwiseData;
		public static Map<String, String> SalesOrderrowwiseData;
		public static Map<String, String> StockUpdaterowwiseData;
		
		
		public static String Cess;
		public static String AdlCsAmt;
		public static String MRP;
		public static String BasicCost;
		public static String DiscountPer1;
		public static String DiscountPer2;
		public static String DiscountPer3;
		public static String GSTPer;
		public static String DiscountPer;
		public static String FromTime;
		public static String ToTime;
		public static String Days;
		public static String AddDiscountPer;
		public static String NetSellingPrice;
		public static String spfixing;
		public static String netcost;
		public static String WPrice1;
		public static String WPrice2;
		public static String WPrice3;
		public static String WAPrice1;
		public static String WAPrice2;
		public static String WAPrice3;
		public static String Batchno;
		public static String Batchno1;
		
		public static String Category;
		public static String Department;
		public static String GrpCode;
		public static String Brand;
		public static String ItemName;
		public static String AverageCost;
		public static String ItemCode;
		public static String ItemCode1;
		public static String ItemType;
		public static String Vendor;
		public static String Bulk;
		public static String Child;
		public static String UOMPurchase;
		public static String SalesUOM;
		public static String StockType;
		public static String Batch;
		
		public static String ShortName;
		public static String Remarks;
		public static String WareHouse;
		public static String Manufacture;
		public static String Merchandise;
		public static String Style;
		public static String Size;
		public static String ModelNo;
		public static String Origin;
		public static String SubCategory;
		public static String Package;
		public static String CCode;
		public static String Class;
		public static String SubClass;
		public static String Basis;
		public static String Bin;
		public static String Section;
		public static String Shelf;
		public static String Weight;
		public static String Height;
		public static String Width;
		public static String Length;
		public static String Purchasetype;
		public static String Departmentcode;
		public static String Departmentname;
		public static String Personincharge;
		public static String Discount;
		public static String RangeFrom;
		public static String RangeTo;
		public static String Remark;
		public static String Categorycode;
		public static String Categoryname;
		public static String Billno;
		public static String Billdate;
		public static String Date;
		public static String EarnedMargin;
		public static String FromDate;
		public static String ToDate;
		public static String Mode;
		public static String Earnedmarginclick;
		public static String MRPclick;
		public static String Netcostclick;
		public static String NewFromDate;
		public static String NewToDate;
		public static String Selectall;
		public static String GrossAmount;
		public static String GST;
		public static String TotalAmount;
		public static String AddDed;
		public static String TotalPayable;
		public static String Subcategorycode;
		public static String Subcategoryname;
		public static String Discounts;
		public static String Brandcode;
		public static String Brandname;
		public static String search;
		public static String InvQty;
		public static String RecvQty;
		public static String DiscP;
		public static String SDA;
		public static String DiscA;
		public static String SDP;
		public static String D1;
		public static String D2;
		public static String D3;
		public static String BillAmt;
		public static String Batch2;
		public static String Batch1;
		public static String Floorcode;
		public static String Description;
		public static String Classcode;
		public static String Subclasscode;
		public static String Itemtypecode;
		public static String foc;
		public static String Taxcode;
		public static String IGST;
		public static String SGST;
		public static String CGST;
		public static String Uomcode;
		public static String Units;
		public static String Qty;
		public static String Qty1;
		public static String PackageInventory;
		public static String WQty;
		public static String Parentcode;
		public static String Bincode;
		public static String LocationCode;
		public static String ShelfCode;
		public static String WarehouseCode;
		public static String WarehouseName;
		public static String Address;
		public static String Address1;
		public static String Address2;
		public static String Pincode;
		public static String Phone;
		public static String Fax;
		public static String Netcost;
		public static String SizeCode;
		public static String Batchrowno;
		public static String Vendorbillno;
		public static String Gidno;
		public static String StyleCode;
		public static String Origion;
		public static String Baseuomcode;
		public static String Baseuomdescription;
		public static String Vendorno;
		public static String Reason;
		public static String Dicountcode;
		public static String Type;
		public static String Zonecode;
		public static String ZoneName;
		public static String PoNo;
		public static String CompanyCode;
		public static String CompanyName;
		public static String Amount;
		public static String PaymentDate;
		public static String Refno;
		public static String RefDate;
		public static String AdjtypeCode;
		public static String AdjtypeName;
		public static String MerchandiseCode;
		public static String Summary;
		public static String Proceed;
		public static String NewVendornum;
		public static String Status;
		public static String ManufacturerCode;
		public static String ManufacturerName;
		public static String Email;
		public static String MinMax;
		public static String Bulkchild;
		public static String Presupplywise;
		public static String Basedoninventory;
		public static String Soldqty;
		public static String Reorderbynoofdays;
		public static String Soldqtyinlastpurchase;
		public static String Reqtycycledays;
		public static String Barcode;
		public static String LocationCode1;
		public static String LocationCode2;
		public static String Price;
		public static String Batch3;
		public static String Selectfield;
		public static String Changefield;
		public static String OrigionCode;
		public static String Transportname;
		public static String Person;
		public static String URL;
		public static String Batch4;
		public static String Batch5;
		public static String Dateformat;
		public static String Template;
		public static String Printername;
		public static String result;
		public static String MinQty;
		public static String MaxQty;
		public static String ReorderQty;
		public static String Cycledays;
		public static String Orderby;
		public static String CheckBox1;
		public static String CheckBox2;
		public static String Expireddate;
		public static String SerialnoEntry;
		public static String AutoPO;
		public static String Packageitem;
		public static String Loyality;
		public static String Special;
		public static String ShelfStorage;
		public static String HideDataOnBarcode;
		public static String Markingitem;
		public static String NeedBarcodePrint;
		public static String AllowCostEditinGRN;
		public static String Weightbased;
		public static String PurchaseOrder;
		public static String GRNPurchase;
		public static String PointOfSale;
		public static String AllowNegative;
		public static String TransferDC;
		public static String EligibilityQty;
		public static String SalesReturn;
		public static String OrderBooking;
		public static String Estimation;
		public static String Quatation;
		public static String OnlineOrder;
		public static String Purchasereturn;
		public static String inventorysearch;
		public static String Chequeno;
		public static String City;
		public static String NoOfRecords;
		public static String Paymode;
		public static String Issued;
		public static String UnIssued;
		public static String All;
		public static String CreditLimit;
		public static String CreditDays;
		public static String HoldInv;
		public static String AllInv;
		public static String BankCode;
		public static String Paymode1;
		public static String BankCode1;
		public static String ChequeNo;
		public static String Invoiceno;
		public static String Customername;
		public static String ChequeDate;
		public static String Cashier;
		public static String Terminal;
		public static String CustomerCode;
		public static String MinAmt;
		public static String MaxAmt;
		public static String CashSales;
		public static String CreditSales;
		public static String CancelBill;
		public static String ExchangeBill;
		public static String DiscountBill;
		public static String SalesReturnBill;
		public static String Path;
		public static String Filter;
		

		
		
		
	}
	
	

}
