package com.unipro.test.framework;

import java.util.Map;

import com.google.common.collect.Table;

public class Globals {

	
	public static Map<String, Table<String, String, String>> excelSheetData;

	public static class Inventory {
		final public static String SHEETNAME = "Inventory";
		final public static String SHEETNAME1 = "Department";
		final public static String SHEETNAME2 = "Category";
		final public static String SHEETNAME3 = "GAcreate";
		final public static String SHEETNAME4 = "Subcategory";
		final public static String SHEETNAME5 = "Brand";
		final public static String SHEETNAME6 = "GRNcreate";
		final public static String SHEETNAME7 = "Floor";
		final public static String SHEETNAME8 = "Purchaseorder";
		final public static String SHEETNAME9 = "Class";
		final public static String SHEETNAME10 = "Subclass";
		final public static String SHEETNAME11 = "Itemtype";
		final public static String SHEETNAME12 = "Purchasereturn";
		final public static String SHEETNAME13 = "Tax";
		final public static String SHEETNAME14 = "Uom";
		final public static String SHEETNAME15 = "Section";
		final public static String SHEETNAME16 = "Bin";
		final public static String SHEETNAME17 = "PurchasereturnReq";
		final public static String SHEETNAME18 = "Shelf";
		final public static String SHEETNAME19 = "Warehouse";
		final public static String SHEETNAME20 = "Size";
		final public static String SHEETNAME21 = "Style";
		final public static String SHEETNAME22 = "Baseuom";
		final public static String SHEETNAME23 = "CreditDebitnote";
		final public static String SHEETNAME24 = "AddDed";
		final public static String SHEETNAME25 = "Zone";
		final public static String SHEETNAME26 = "PoVendorChange";
		final public static String SHEETNAME27 = "CompanySettings";
		final public static String SHEETNAME28 = "DisplayandContracts";
		final public static String SHEETNAME29 = "StockAdjustmentType";
		final public static String SHEETNAME30 = "Merchandise";
		final public static String SHEETNAME31 = "ConsolidatedPocreate";
		final public static String SHEETNAME32 = "PurchaseOrderStatus";
		final public static String SHEETNAME33 = "Manufacturer";
		final public static String SHEETNAME34 = "AutoPO";
		final public static String SHEETNAME35 = "Vendorcatelog";
		final public static String SHEETNAME36 = "ConsolidatedPO";
		
		
		public static Table<String, String, String> inventorySheetData;
		public static Table<String, String, String> DepartmentSheetData;
		public static Table<String, String, String> CategorySheetData;
		public static Table<String, String, String> GRNcreateSheetData;
		public static Table<String, String, String> GAcreateSheetData;
		public static Table<String, String, String> SubcategorySheetData;
		public static Table<String, String, String> BrandSheetData;
		public static Table<String, String, String> FloorSheetData;
		public static Table<String, String, String> PurchaseorderSheetData;
		public static Table<String, String, String> ClassSheetData;
		public static Table<String, String, String> SubclassSheetData;
		public static Table<String, String, String> ItemtypeSheetData;
		public static Table<String, String, String> PurchasereturnSheetData;
		public static Table<String, String, String> PurchasereturnReqSheetData;
		public static Table<String, String, String> TaxSheetData;
		public static Table<String, String, String> UomSheetData;
		public static Table<String, String, String> SectionSheetData;
		public static Table<String, String, String> BinSheetData;
		public static Table<String, String, String> ShelfSheetData;
		public static Table<String, String, String> WarehouseSheetData;
		public static Table<String, String, String> SizeSheetData;
		public static Table<String, String, String> StyleSheetData;
		public static Table<String, String, String> BaseuomSheetData;
		public static Table<String, String, String> CreditDebitnoteSheetData;
		public static Table<String, String, String> AddDedSheetData;
		public static Table<String, String, String> ZoneSheetData;
		public static Table<String, String, String> PoVendorChangeSheetData;
		public static Table<String, String, String> CompanySettingsSheetData;
		public static Table<String, String, String> DisplayandContractsSheetData;
		public static Table<String, String, String> StockAdjustmentTypeSheetData;
		public static Table<String, String, String> MerchandiseSheetData;
		public static Table<String, String, String> ConsolidatedPocreateSheetData;
		public static Table<String, String, String> PurchaseOrderStatusSheetData;
		public static Table<String, String, String> ManufacturerSheetData;
		public static Table<String, String, String> AutoPOSheetData;
		public static Table<String, String, String> VendorcatelogSheetData;
		public static Table<String, String, String> ConsolidatedPOSheetData;
		
		public static Map<String, String> inventoryrowwiseData;
		public static Map<String, String> DepartmentrowwiseData;
		public static Map<String, String> CategoryrowwiseData;
		public static Map<String, String> GAcreaterowwiseData;
		public static Map<String, String> SubcategoryrowwiseData;
		public static Map<String, String> BrandrowwiseData;
		public static Map<String, String> GRNcreaterowwiseData;
		public static Map<String, String> FloorrowwiseData;
		public static Map<String, String> PurchaseorderrowwiseData;
		public static Map<String, String> ClassrowwiseData;
		public static Map<String, String> SubclassrowwiseData;
		public static Map<String, String> ItemtyperowwiseData;
		public static Map<String, String> PurchasereturnrowwiseData;
		public static Map<String, String> TaxrowwiseData;
		public static Map<String, String> UomrowwiseData;
		public static Map<String, String> SectionrowwiseData;
		public static Map<String, String> BinrowwiseData;
		public static Map<String, String> PurchasereturnReqrowwiseData;
		public static Map<String, String> ShelfrowwiseData;
		public static Map<String, String> WarehouserowwiseData;
		public static Map<String, String> SizerowwiseData;
		public static Map<String, String> StylerowwiseData;
		public static Map<String, String> BaseuomrowwiseData;
		public static Map<String, String> CreditDebitnoterowwiseData;
		public static Map<String, String> AddDedrowwiseData;
		public static Map<String, String> ZonerowwiseData;
		public static Map<String, String> PoVendorChangerowwiseData;
		public static Map<String, String> CompanySettingsrowwiseData;
		public static Map<String, String> DisplayandContractsrowwiseData;
		public static Map<String, String> StockAdjustmentTyperowwiseData;
		public static Map<String, String> MerchandiserowwiseData;
		public static Map<String, String> ConsolidatedPocreaterowwiseData;
		public static Map<String, String> PurchaseOrderStatusrowwiseData;
		public static Map<String, String> ManufacturerrowwiseData;
		public static Map<String, String> AutoPOrowwiseData;
		public static Map<String, String> VendorcatelogrowwiseData;
		public static Map<String, String> ConsolidatedPOrowwiseData;
	
		
		
		
		public static String Cess;
		public static String AdlCsAmt;
		public static String MRP;
		public static String BasicCost;
		public static String DiscountPer1;
		public static String DiscountPer2;
		public static String DiscountPer3;
		public static String GSTPer;
		public static String DiscountPer;
		public static String AddDiscountPer;
		public static String NetSellingPrice;
		public static String spfixing;
		public static String netcost;
		public static String WPrice1;
		public static String WPrice2;
		public static String WPrice3;
		
		public static String Category;
		public static String Department;
		public static String Brand;
		public static String ItemName;
		public static String ItemCode;
		public static String ItemType;
		public static String Vendor;
		public static String UOMPurchase;
		public static String SalesUOM;
		public static String StockType;
		public static String Batch;
		
		public static String ShortName;
		public static String Remarks;
		public static String WareHouse;
		public static String Manufacture;
		public static String Merchandise;
		public static String Style;
		public static String Size;
		public static String ModelNo;
		public static String Origin;
		public static String SubCategory;
		public static String Package;
		public static String CCode;
		public static String Class;
		public static String SubClass;
		public static String Bin;
		public static String Section;
		public static String Shelf;
		public static String Weight;
		public static String Height;
		public static String Width;
		public static String Length;
		public static String Departmentcode;
		public static String Departmentname;
		public static String Personincharge;
		public static String Discount;
		public static String Remark;
		public static String Categorycode;
		public static String Categoryname;
		public static String Billno;
		public static String Billdate;
		public static String Date;
		public static String GrossAmount;
		public static String GST;
		public static String TotalAmount;
		public static String AddDed;
		public static String TotalPayable;
		public static String Subcategorycode;
		public static String Subcategoryname;
		public static String Discounts;
		public static String Brandcode;
		public static String Brandname;
		public static String search;
		public static String InvQty;
		public static String RecvQty;
		public static String DiscP;
		public static String SDA;
		public static String DiscA;
		public static String SDP;
		public static String D1;
		public static String D2;
		public static String D3;
		public static String BillAmt;
		public static String Batch2;
		public static String Batch1;
		public static String Floorcode;
		public static String Description;
		public static String Classcode;
		public static String Subclasscode;
		public static String Itemtypecode;
		public static String foc;
		public static String Taxcode;
		public static String IGST;
		public static String SGST;
		public static String CGST;
		public static String Uomcode;
		public static String Units;
		public static String Qty;
		public static String Bincode;
		public static String LocationCode;
		public static String ShelfCode;
		public static String WarehouseCode;
		public static String WarehouseName;
		public static String Address;
		public static String Address1;
		public static String Address2;
		public static String Pincode;
		public static String Phone;
		public static String Fax;
		public static String Netcost;
		public static String SizeCode;
		public static String Batchrowno;
		public static String Vendorbillno;
		public static String Gidno;
		public static String StyleCode;
		public static String Origion;
		public static String Baseuomcode;
		public static String Baseuomdescription;
		public static String Vendorno;
		public static String Reason;
		public static String Dicountcode;
		public static String Type;
		public static String Zonecode;
		public static String ZoneName;
		public static String PoNo;
		public static String CompanyCode;
		public static String CompanyName;
		public static String Amount;
		public static String PaymentDate;
		public static String Refno;
		public static String RefDate;
		public static String AdjtypeCode;
		public static String AdjtypeName;
		public static String MerchandiseCode;
		public static String Summary;
		public static String Proceed;
		public static String NewVendornum;
		public static String Status;
		public static String ManufacturerCode;
		public static String ManufacturerName;
		public static String Email;
		public static String MinMax;
		public static String Bulkchild;
		public static String Presupplywise;
		public static String Basedoninventory;
		public static String Soldqty;
		public static String Reorderbynoofdays;
		public static String Soldqtyinlastpurchase;
		public static String Reqtycycledays;
		public static String Barcode;
		public static String LocationCode1;
		public static String LocationCode2;

		
		
		
	}
	
	

}
