package com.unipro.test.framework;

import java.util.Map;

import com.google.common.collect.Table;

public class Globals {

	
	public static Map<String, Table<String, String, String>> excelSheetData;

	public static class Inventory {
		final public static String SHEETNAME = "Inventory";
		final public static String SHEETNAME1 = "Department";
		final public static String SHEETNAME2 = "Category";
		final public static String SHEETNAME3 = "GAcreate";
		final public static String SHEETNAME4 = "Subcategory";
		final public static String SHEETNAME5 = "Brand";
		final public static String SHEETNAME6 = "GRNcreate";
		final public static String SHEETNAME7 = "Floor";
		final public static String SHEETNAME8 = "Purchaseorder";
		final public static String SHEETNAME9 = "Class";
		final public static String SHEETNAME10 = "Subclass";
		final public static String SHEETNAME11 = "Itemtype";
		final public static String SHEETNAME12 = "Purchasereturn";
		final public static String SHEETNAME13 = "Tax";
		final public static String SHEETNAME14 = "Uom";
		final public static String SHEETNAME15 = "Section";
		final public static String SHEETNAME16 = "Bin";
		final public static String SHEETNAME17 = "PurchasereturnReq";
		final public static String SHEETNAME18 = "Shelf";
		final public static String SHEETNAME19 = "Warehouse";
		final public static String SHEETNAME20 = "Size";
		final public static String SHEETNAME21 = "Style";
		final public static String SHEETNAME22 = "Baseuom";
		final public static String SHEETNAME23 = "CreditDebitnote";
		final public static String SHEETNAME24 = "AddDed";
		final public static String SHEETNAME25 = "Zone";
		final public static String SHEETNAME26 = "PoVendorChange";
		final public static String SHEETNAME27 = "CompanySettings";
		final public static String SHEETNAME28 = "DisplayandContracts";
		final public static String SHEETNAME29 = "StockAdjustmentType";
		final public static String SHEETNAME30 = "Merchandise";
		final public static String SHEETNAME31 = "ConsolidatedPocreate";
		final public static String SHEETNAME32 = "PurchaseOrderStatus";
		final public static String SHEETNAME33 = "Manufacturer";
		final public static String SHEETNAME34 = "AutoPO";
		final public static String SHEETNAME35 = "Vendorcatelog";
		final public static String SHEETNAME36 = "ConsolidatedPO";
		final public static String SHEETNAME37 = "Inventorychange";
		final public static String SHEETNAME38 = "InventoryCostReset";
		final public static String SHEETNAME39 = "Inventorymovement";
		final public static String SHEETNAME40 = "Origion";
		final public static String SHEETNAME41 = "Transport";
		final public static String SHEETNAME42 = "Barcode";
		final public static String SHEETNAME43 = "InventoryHistory";
		final public static String SHEETNAME44 = "ReorderSettings";
		final public static String SHEETNAME45 = "InventoryParentChildSetting";
		final public static String SHEETNAME46 = "Distribution";
		final public static String SHEETNAME47 = "InventoryParameter";
		final public static String SHEETNAME48 = "PackageInventory";
		final public static String SHEETNAME49 = "RefillingScheduling";
		final public static String SHEETNAME50 = "LocationWisePriceChange";
		final public static String SHEETNAME51 = "PriceChangeBatchItem";
		final public static String SHEETNAME52 = "PriceChangeNonBatchItem";
		final public static String SHEETNAME53 = "PriceImportExport";
		final public static String SHEETNAME54 = "FreeItem";
		final public static String SHEETNAME55 = "NormalPromotion";
		final public static String SHEETNAME56 = "OtherPromotion";
		final public static String SHEETNAME57 = "DayBasedPromotion";
		final public static String SHEETNAME58 = "RevokePromotion";
		final public static String SHEETNAME59 = "Payments";
		final public static String SHEETNAME60 = "Creditinvoice";
		final public static String SHEETNAME61 = "CustomerReceipts";
		final public static String SHEETNAME62 = "Billcancel";
		final public static String SHEETNAME63 = "SalesTransaction";
		final public static String SHEETNAME64 = "StockAdjustment";
		final public static String SHEETNAME65 = "SalesOrder";
		final public static String SHEETNAME66 = "StockUpdate";
		final public static String SHEETNAME67 = "StockUpdatePosting";
		final public static String SHEETNAME68 = "ExpiredDateChange";
		final public static String SHEETNAME69 = "StockReset";
		final public static String SHEETNAME70 = "TransferOut";
		final public static String SHEETNAME71 = "TransferIn";
		final public static String SHEETNAME72 = "StockRequestProcess";
		final public static String SHEETNAME73 = "CompanyMaster";
		final public static String SHEETNAME74 = "LocationNew";
		final public static String SHEETNAME75 = "ReasonMasterNew";
		final public static String SHEETNAME76 = "TerminalNew";
		final public static String SHEETNAME77 = "CustomerNew";
		final public static String SHEETNAME78 = "TermsNew";
		final public static String SHEETNAME79 = "DisplayandContractNew";
		final public static String SHEETNAME80 = "BankNew";
		final public static String SHEETNAME81 = "SalesManNew";
		final public static String SHEETNAME82 = "DeliveryManNew";
		final public static String SHEETNAME83 = "BrandWiseSalesManCommission";
		final public static String SHEETNAME84 = "ItemWiseSalesManCommission";
		final public static String SHEETNAME85 = "SalesManComission";
		final public static String SHEETNAME86 = "POSPaymentNew";
		final public static String SHEETNAME87 = "PaymodeNew";
		final public static String SHEETNAME88 = "VehicleMasterNew";
		final public static String SHEETNAME89 = "HomeDeliveryTrayNew";
		final public static String SHEETNAME90 = "BarCodePrinterNew";
		final public static String SHEETNAME91 = "PickerMasterNew";
		final public static String SHEETNAME92 = "ParamMasterNew";
		final public static String SHEETNAME93 = "VendorMaster";
		final public static String SHEETNAME94 = "VendorAnalysis";
		final public static String SHEETNAME95 = "PurchaseAnalysis";
		final public static String SHEETNAME96 = "SalesPerformance";
		final public static String SHEETNAME97 = "SalesAnalysisReport";
		final public static String SHEETNAME98 = "SalesAnalysisPromotionEvents";
		final public static String SHEETNAME99 = "SalesAnalysisMemberReport";
		final public static String SHEETNAME100 = "TerminalWiseGstAnalysis";
		final public static String SHEETNAME101 = "GstAnalysis";
		final public static String SHEETNAME102 = "GSTR";
		final public static String SHEETNAME103 = "LocationStockMovement";
		final public static String SHEETNAME104 = "LocationWiseSales";
		final public static String SHEETNAME105 = "AuditTrails";
		final public static String SHEETNAME106 = "Registration";
		final public static String SHEETNAME107 = "LinkAccount";
		final public static String SHEETNAME108 = "AccountSettlement";
		final public static String SHEETNAME109 = "MasterReports";
		final public static String SHEETNAME110 = "InventoryList";
		final public static String SHEETNAME111 = "InventoryMovementWiseReport";
		final public static String SHEETNAME112 = "SalesWiseReport";
		final public static String SHEETNAME113 = "PaymentandReceipts";
		final public static String SHEETNAME114 = "PuchaseGRNReports";
		final public static String SHEETNAME115 = "PurchaseOrderReport";
		final public static String SHEETNAME116 = "PurchaseReturnReqReports";
		final public static String SHEETNAME117 = "VendorOutstanding";
		final public static String SHEETNAME118 = "QuickSalesReport";
		final public static String SHEETNAME119 = "SalesMoreReport";
		final public static String SHEETNAME120 = "SalesAuditReport";
		final public static String SHEETNAME121 = "CreditandDueSaleReport";
		final public static String SHEETNAME122 = "SalesReturnReport";
		final public static String SHEETNAME123 = "MemberWiseSales";
		final public static String SHEETNAME124 = "LocationWiseItemWiseSales";
		final public static String SHEETNAME125 = "PreSalesReport";
		final public static String SHEETNAME126 = "LocationWiseSalesReport";
		final public static String SHEETNAME127 = "PromotionReports";
		final public static String SHEETNAME128 = "StockReports";
		final public static String SHEETNAME129 = "SettlementReports";
		final public static String SHEETNAME130 = "CustomerReceiptReport";
		final public static String SHEETNAME131 = "LocationDueReceipt";
		final public static String SHEETNAME132 = "TransferReport";
		final public static String SHEETNAME133 = "AttributeReport";
		final public static String SHEETNAME134 = "StockAgingReport";
		final public static String SHEETNAME135 = "TransferStatusQuery";
		
		                                          
		public static Table<String, String, String> inventorySheetData;
		public static Table<String, String, String> DepartmentSheetData;
		public static Table<String, String, String> CategorySheetData;
		public static Table<String, String, String> GRNcreateSheetData;
		public static Table<String, String, String> GAcreateSheetData;
		public static Table<String, String, String> SubcategorySheetData;
		public static Table<String, String, String> BrandSheetData;
		public static Table<String, String, String> FloorSheetData;
		public static Table<String, String, String> PurchaseorderSheetData;
		public static Table<String, String, String> ClassSheetData;
		public static Table<String, String, String> SubclassSheetData;
		public static Table<String, String, String> ItemtypeSheetData;
		public static Table<String, String, String> PurchasereturnSheetData;
		public static Table<String, String, String> PurchasereturnReqSheetData;
		public static Table<String, String, String> TaxSheetData;
		public static Table<String, String, String> UomSheetData;
		public static Table<String, String, String> SectionSheetData;
		public static Table<String, String, String> BinSheetData;
		public static Table<String, String, String> ShelfSheetData;
		public static Table<String, String, String> WarehouseSheetData;
		public static Table<String, String, String> SizeSheetData;
		public static Table<String, String, String> StyleSheetData;
		public static Table<String, String, String> BaseuomSheetData;
		public static Table<String, String, String> CreditDebitnoteSheetData;
		public static Table<String, String, String> AddDedSheetData;
		public static Table<String, String, String> ZoneSheetData;
		public static Table<String, String, String> PoVendorChangeSheetData;
		public static Table<String, String, String> CompanySettingsSheetData;
		public static Table<String, String, String> DisplayandContractsSheetData;
		public static Table<String, String, String> StockAdjustmentTypeSheetData;
		public static Table<String, String, String> MerchandiseSheetData;
		public static Table<String, String, String> ConsolidatedPocreateSheetData;
		public static Table<String, String, String> PurchaseOrderStatusSheetData;
		public static Table<String, String, String> ManufacturerSheetData;
		public static Table<String, String, String> AutoPOSheetData;
		public static Table<String, String, String> VendorcatelogSheetData;
		public static Table<String, String, String> ConsolidatedPOSheetData;
		public static Table<String, String, String> InventorychangeSheetData;
		public static Table<String, String, String> InventoryCostResetSheetData;
		public static Table<String, String, String> InventorymovementSheetData;
		public static Table<String, String, String> OrigionSheetData;
		public static Table<String, String, String> TransportSheetData;
		public static Table<String, String, String> BarcodeSheetData;
		public static Table<String, String, String> InventoryHistorySheetData;
		public static Table<String, String, String> ReorderSettingsSheetData;
		public static Table<String, String, String> InventoryParentChildSettingSheetData;
		public static Table<String, String, String> DistributionSheetData;
		public static Table<String, String, String> InventoryParameterSheetData;
		public static Table<String, String, String> PackageinventorySheetData;
		public static Table<String, String, String> RefillingSchedulingSheetData;
		public static Table<String, String, String> LocationWisePriceChangeSheetData;
		public static Table<String, String, String> PriceChangeBatchItemSheetData;
		public static Table<String, String, String> PriceChangeNonBatchItemItemSheetData;
		public static Table<String, String, String> PriceImportExportSheetData;
		public static Table<String, String, String> FreeItemSheetData;
		public static Table<String, String, String> NormalPromotionSheetData;
		public static Table<String, String, String> OtherPromotionSheetData;
		public static Table<String, String, String> DayBasedPromotionSheetData;
		public static Table<String, String, String> RevokePromotionSheetData;
		public static Table<String, String, String> PaymentsSheetData;
		public static Table<String, String, String> CreditinvoiceSheetData;
		public static Table<String, String, String> CustomerReceiptsSheetData;
		public static Table<String, String, String> BillcancelSheetData;
		public static Table<String, String, String> SalesTransactionSheetData;
		public static Table<String, String, String> StockAdjustmentSheetData;
		public static Table<String, String, String> SalesOrderSheetData;
		public static Table<String, String, String> StockUpdateSheetData;
		public static Table<String, String, String> StockUpdatePostingSheetData;
		public static Table<String, String, String> ExpiredDateChangeSheetData;
		public static Table<String, String, String> StockResetSheetData;
		public static Table<String, String, String> TransferOutSheetData;
		public static Table<String, String, String> TransferInSheetData;
		public static Table<String, String, String> StockRequestProcessSheetData;
		public static Table<String, String, String> CompanyMasterSheetData;
		public static Table<String, String, String> LocationNewSheetData;
		public static Table<String, String, String> ReasonMasterNewSheetData;
		public static Table<String, String, String> TerminalNewSheetData;
		public static Table<String, String, String> CustomerNewSheetData;
		public static Table<String, String, String> TermsNewSheetData;
		public static Table<String, String, String> DisplayandContractNewSheetData;
		public static Table<String, String, String> BankNewSheetData;
		public static Table<String, String, String> SalesManNewSheetData;
		public static Table<String, String, String> DeliveryManNewSheetData;
		public static Table<String, String, String> BrandWiseSalesManCommissionSheetData;
		public static Table<String, String, String> ItemWiseSalesManCommissionSheetData;
		public static Table<String, String, String> SalesManComissionSheetData;
		public static Table<String, String, String> POSPaymentNewSheetData;
		public static Table<String, String, String> PaymodeNewSheetData;
		public static Table<String, String, String> VehicleMasterNewSheetData;
		public static Table<String, String, String> HomeDeliveryTrayNewSheetData;
		public static Table<String, String, String> BarCodePrinterNewSheetData;
		public static Table<String, String, String> PickerMasterNewSheetData;
		public static Table<String, String, String> ParamMasterNewSheetData;
		public static Table<String, String, String> VendorMasterSheetData;
		public static Table<String, String, String> VendorAnalysisSheetData;
		public static Table<String, String, String> PurchaseAnalysisSheetData;
		public static Table<String, String, String> SalesPerformanceSheetData;
		public static Table<String, String, String> SalesAnalysisReportSheetData;
		public static Table<String, String, String> SalesAnalysisPromotionEventsSheetData;
		public static Table<String, String, String> SalesAnalysisMemberReportSheetData;
		public static Table<String, String, String> TerminalWiseGstAnalysisSheetData;
		public static Table<String, String, String> GstAnalysisSheetData;
		public static Table<String, String, String> GSTRSheetData;
		public static Table<String, String, String> LocationStockMovementSheetData;
		public static Table<String, String, String> LocationWiseSalesSheetData;
		public static Table<String, String, String> AuditTrailsSheetData;
		public static Table<String, String, String> RegistrationSheetData;
		public static Table<String, String, String> LinkAccountSheetData;
		public static Table<String, String, String> AccountSettlementSheetData;
		public static Table<String, String, String> MasterReportsSheetData;
		public static Table<String, String, String> InventoryListSheetData;
		public static Table<String, String, String> InventoryMovementWiseReportSheetData;
		public static Table<String, String, String> SalesWiseReportSheetData;
		public static Table<String, String, String> PaymentandReceiptsSheetData;
		public static Table<String, String, String> PuchaseGRNReportsSheetData;
		public static Table<String, String, String> PurchaseOrderReportSheetData;
		public static Table<String, String, String> PurchaseReturnReqReportsSheetData;
		public static Table<String, String, String> VendorOutstandingSheetData;
		public static Table<String, String, String> QuickSalesReportSheetData;
		public static Table<String, String, String> SalesMoreReportSheetData;
		public static Table<String, String, String> SalesAuditReportSheetData;
		public static Table<String, String, String> CreditandDueSaleReportSheetData;
		public static Table<String, String, String> SalesReturnReportSheetData;
		public static Table<String, String, String> MemberWiseSalesSheetData;
		public static Table<String, String, String> LocationWiseItemWiseSalesSheetData;
		public static Table<String, String, String> PreSalesReportSheetData;
		public static Table<String, String, String> LocationWiseSalesReportSheetData;
		public static Table<String, String, String> PromotionReportsSheetData;
		public static Table<String, String, String> StockReportsSheetData;
		public static Table<String, String, String> SettlementReportsSheetData;
		public static Table<String, String, String> CustomerReceiptReportSheetData;
		public static Table<String, String, String> LocationDueReceiptSheetData;
		public static Table<String, String, String> TransferReportSheetData;
		public static Table<String, String, String> AttributeReportSheetData;
		public static Table<String, String, String> StockAgingReportSheetData;
		public static Table<String, String, String> TransferStatusQuerySheetData;
		
		
		public static Map<String, String> inventoryrowwiseData;
		public static Map<String, String> DepartmentrowwiseData;
		public static Map<String, String> CategoryrowwiseData;
		public static Map<String, String> GAcreaterowwiseData;
		public static Map<String, String> SubcategoryrowwiseData;
		public static Map<String, String> BrandrowwiseData;
		public static Map<String, String> GRNcreaterowwiseData;
		public static Map<String, String> FloorrowwiseData;
		public static Map<String, String> PurchaseorderrowwiseData;
		public static Map<String, String> ClassrowwiseData;
		public static Map<String, String> SubclassrowwiseData;
		public static Map<String, String> ItemtyperowwiseData;
		public static Map<String, String> PurchasereturnrowwiseData;
		public static Map<String, String> TaxrowwiseData;
		public static Map<String, String> UomrowwiseData;
		public static Map<String, String> SectionrowwiseData;
		public static Map<String, String> BinrowwiseData;
		public static Map<String, String> PurchasereturnReqrowwiseData;
		public static Map<String, String> ShelfrowwiseData;
		public static Map<String, String> WarehouserowwiseData;
		public static Map<String, String> SizerowwiseData;
		public static Map<String, String> StylerowwiseData;
		public static Map<String, String> BaseuomrowwiseData;
		public static Map<String, String> CreditDebitnoterowwiseData;
		public static Map<String, String> AddDedrowwiseData;
		public static Map<String, String> ZonerowwiseData;
		public static Map<String, String> PoVendorChangerowwiseData;
		public static Map<String, String> CompanySettingsrowwiseData;
		public static Map<String, String> DisplayandContractsrowwiseData;
		public static Map<String, String> StockAdjustmentTyperowwiseData;
		public static Map<String, String> MerchandiserowwiseData;
		public static Map<String, String> ConsolidatedPocreaterowwiseData;
		public static Map<String, String> PurchaseOrderStatusrowwiseData;
		public static Map<String, String> ManufacturerrowwiseData;
		public static Map<String, String> AutoPOrowwiseData;
		public static Map<String, String> VendorcatelogrowwiseData;
		public static Map<String, String> ConsolidatedPOrowwiseData;
		public static Map<String, String> InventorychangerowwiseData;
		public static Map<String, String> InventoryCostResetrowwiseData;
		public static Map<String, String> InventorymovementrowwiseData;
		public static Map<String, String> OrigionrowwiseData;
		public static Map<String, String> TransportrowwiseData;
		public static Map<String, String> BarcoderowwiseData;
		public static Map<String, String> InventoryHistoryrowwiseData;
		public static Map<String, String> ReorderSettingsrowwiseData;
		public static Map<String, String> InventoryParentChildSettingrowwiseData;
		public static Map<String, String> DistributionrowwiseData;
		public static Map<String, String> InventoryParameterrowwiseData;
		public static Map<String, String> PackageinventoryrowwiseData;
		public static Map<String, String> RefillingSchedulingrowwiseData;
		public static Map<String, String> LocationWisePriceChangerowwiseData;
		public static Map<String, String> PriceChangeBatchItemrowwiseData;
		public static Map<String, String> PriceChangeNonBatchItemItemrowwiseData;
		public static Map<String, String> PriceImportExportrowwiseData;
		public static Map<String, String> FreeItemrowwiseData;
		public static Map<String, String> NormalPromotionrowwiseData;
		public static Map<String, String> OtherPromotionrowwiseData;
		public static Map<String, String> DayBasedPromotionrowwiseData;
		public static Map<String, String> RevokePromotionrowwiseData;
		public static Map<String, String> PaymentsrowwiseData;
		public static Map<String, String> CreditinvoicerowwiseData;
		public static Map<String, String> CustomerReceiptsrowwiseData;
		public static Map<String, String> BillcancelrowwiseData;
		public static Map<String, String> SalesTransactionrowwiseData;
		public static Map<String, String> StockAdjustmentrowwiseData;
		public static Map<String, String> SalesOrderrowwiseData;
		public static Map<String, String> StockUpdaterowwiseData;
		public static Map<String, String> StockUpdatePostingrowwiseData;
		public static Map<String, String> ExpiredDateChangerowwiseData;
		public static Map<String, String> StockResetrowwiseData;
		public static Map<String, String> TransferOutrowwiseData;
		public static Map<String, String> TransferInrowwiseData;
		public static Map<String, String> StockRequestProcessrowwiseData;
		public static Map<String, String> CompanyMasterrowwiseData;
		public static Map<String, String> LocationNewrowwiseData;
		public static Map<String, String> ReasonMasterNewrowwiseData;
		public static Map<String, String> TerminalNewrowwiseData;
		public static Map<String, String> CustomerNewrowwiseData;
		public static Map<String, String> TermsNewrowwiseData;
		public static Map<String, String> DisplayandContractNewrowwiseData;
		public static Map<String, String> BankNewrowwiseData;
		public static Map<String, String> SalesManNewrowwiseData;
		public static Map<String, String> DeliveryManNewrowwiseData;
		public static Map<String, String> BrandWiseSalesManCommissionrowwiseData;
		public static Map<String, String> ItemWiseSalesManCommissionrowwiseData;
		public static Map<String, String> SalesManCommissionrowwiseData;
		public static Map<String, String> POSPaymentNewrowwiseData;
		public static Map<String, String> PaymodeNewrowwiseData;
		public static Map<String, String> VehicleMasterNewrowwiseData;
		public static Map<String, String> HomeDeliveryTrayNewrowwiseData;
		public static Map<String, String> BarCodePrinterNewrowwiseData;
		public static Map<String, String> PickerMasterNewrowwiseData;
		public static Map<String, String> ParamMasterNewrowwiseData;
		public static Map<String, String> VendorMasterrowwiseData;
		public static Map<String, String> VendorAnalysisrowwiseData;
		public static Map<String, String> PurchaseAnalysisrowwiseData;
		public static Map<String, String> SalesPerformancerowwiseData;
		public static Map<String, String> SalesAnalysisReportrowwiseData;
		public static Map<String, String> SalesAnalysisPromotionEventsrowwiseData;
		public static Map<String, String> SalesAnalysisMemberReportrowwiseData;
		public static Map<String, String> TerminalWiseGstAnalysisrowwiseData;
		public static Map<String, String> GstAnalysisrowwiseData;
		public static Map<String, String> GSTRrowwiseData;
		public static Map<String, String> LocationStockMovementrowwiseData;
		public static Map<String, String> LocationWiseSalesrowwiseData;
		public static Map<String, String> AuditTrailsrowwiseData;
		public static Map<String, String> RegistrationrowwiseData;
		public static Map<String, String> LinkAccountrowwiseData;
		public static Map<String, String> AccountSettlementrowwiseData;
		public static Map<String, String> MasterReportsrowwiseData;
		public static Map<String, String> InventoryListrowwiseData;
		public static Map<String, String> InventoryMovementWiseReportrowwiseData;
		public static Map<String, String> SalesWiseReportrowwiseData;
		public static Map<String, String> PaymentandReceiptsrowwiseData;
		public static Map<String, String> PuchaseGRNReportsrowwiseData;
		public static Map<String, String> PurchaseOrderReportrowwiseData;
		public static Map<String, String> PurchaseReturnReqReportsrowwiseData;
		public static Map<String, String> VendorOutstandingrowwiseData;
		public static Map<String, String> QuickSalesReportrowwiseData;
		public static Map<String, String> SalesMoreReportrowwiseData;
		public static Map<String, String> SalesAuditReportrowwiseData;
		public static Map<String, String> CreditandDueSaleReportrowwiseData;
		public static Map<String, String> SalesReturnReportrowwiseData;
		public static Map<String, String> MemberWiseSalesrowwiseData;
		public static Map<String, String> LocationWiseItemWiseSalesrowwiseData;
		public static Map<String, String> PreSalesReportrowwiseData;
		public static Map<String, String> LocationWiseSalesReportrowwiseData;
		public static Map<String, String> PromotionReportsrowwiseData;
		public static Map<String, String> StockReportsrowwiseData;
		public static Map<String, String> SettlementReportsrowwiseData;
		public static Map<String, String> CustomerReceiptReportrowwiseData;
		public static Map<String, String> LocationDueReceiptrowwiseData;
		public static Map<String, String> TransferReportrowwiseData;
		public static Map<String, String> AttributeReportrowwiseData;
		public static Map<String, String> StockAgingReportrowwiseData;
		public static Map<String, String> TransferStatusQueryrowwiseData;

		

		
		public static String Cess;
		public static String AdlCsAmt;
		public static String MRP;
		public static String BasicCost;
		public static String DiscountPer1;
		public static String DiscountPer2;
		public static String DiscountPer3;
		public static String GSTPer;
		public static String DiscountPer;
		public static String FromTime;
		public static String ToTime;
		public static String Days;
		public static String AddDiscountPer;
		public static String NetSellingPrice;
		public static String spfixing;
		public static String netcost;
		public static String WPrice1;
		public static String WPrice2;
		public static String WPrice3;
		public static String WAPrice1;
		public static String WAPrice2;
		public static String WAPrice3;
		public static String Batchno;
		public static String Batchno1;
		
		
		public static String GrnNo;
		public static String InvNo;
		public static String GrnDate;
		public static String InvDate;
		public static String GaNumber;
		public static String GaDate;
		public static String ItemDesc;
		public static String GrossCost;
		public static String Gst;
		public static String AddCess;
		public static String SpFixing;
		public static String MEarned;
		public static String Wuom;
		public static String Luom;
		public static String GrBasic;
		public static String GrCost;
		public static String GrDisc;
		public static String GrSchm;
		public static String GrGst;
		public static String LastInQty;
		public static String GrcAmt;
		public static String GrAddCess;
		public static String Total;
		public static String GrAmt;
		public static String GstA;
		public static String TotalCessAmt;
		public static String GstCessAmt;
		
		public static String Deduction;
		public static String Addition;
		public static String TRow;
		public static String TQty;
		public static String TBasicCost;
		public static String TotDisc;
		public static String TotSchmDisc;
		public static String TotGrCost;
		
		public static String Category;
		public static String Department;
		public static String GrpCode;
		public static String Brand;
		public static String ItemName;
		public static String AverageCost;
		public static String ItemCode;
		public static String ItemCode1;
		public static String ItemType;
		public static String Vendor;
		public static String VendorName;
		public static String Bulk;
		public static String Child;
		public static String UOMPurchase;
		public static String SalesUOM;
		public static String StockType;
		public static String Batch;
		
		public static String ShortName;
		public static String Remarks;
		public static String WareHouse;
		public static String Manufacture;
		public static String Merchandise;
		public static String Style;
		public static String Size;
		public static String ModelNo;
		public static String Origin;
		public static String SubCategory;
		public static String Package;
		public static String CCode;
		public static String Class;
		public static String SubClass;
		public static String Basis;
		public static String Bin;
		public static String Section;
		public static String Shelf;
		public static String Weight;
		public static String Height;
		public static String Width;
		public static String Length;
		public static String Purchasetype;
		public static String Departmentcode;
		public static String Departmentname;
		public static String Personincharge;
		public static String Discount;
		public static String RangeFrom;
		public static String RangeTo;
		public static String Remark;
		public static String Categorycode;
		public static String Categoryname;
		public static String Billno;
		public static String Billdate;
		public static String Date;
		public static String EarnedMargin;
		public static String FromDate;
		public static String ToDate;
		public static String Mode;
		public static String Earnedmarginclick;
		public static String MRPclick;
		public static String Netcostclick;
		public static String NewFromDate;
		public static String NewToDate;
		public static String Selectall;
		public static String GrossAmount;
		public static String GST;
		public static String TotalAmount;
		public static String AddDed;
		public static String TotalPayable;
		public static String Subcategorycode;
		public static String Subcategoryname;
		public static String Discounts;
		public static String Brandcode;
		public static String Brandname;
		public static String search;
		public static String InvQty;
		public static String RecvQty;
		public static String DiscP;
		public static String SDA;
		public static String DiscA;
		public static String SDP;
		public static String D1;
		public static String D2;
		public static String D3;
		public static String BillAmt;
		public static String Batch2;
		public static String Batch1;
		public static String Floorcode;
		public static String Description;
		public static String Classcode;
		public static String Subclasscode;
		public static String Itemtypecode;
		public static String foc;
		public static String Taxcode;
		public static String IGST;
		public static String SGST;
		public static String CGST;
		public static String Uomcode;
		public static String Units;
		public static String Qty;
		public static String Qty1;
		public static String PackageInventory;
		public static String WQty;
		public static String Parentcode;
		public static String Bincode;
		public static String LocationCode;
		public static String ShelfCode;
		public static String WarehouseCode;
		public static String WarehouseName;
		public static String Address;
		public static String Address1;
		public static String Address2;
		public static String Pincode;
		public static String Phone;
		public static String Fax;
		public static String Netcost;
		public static String NetcostPer;
		
		public static String SizeCode;
		public static String Batchrowno;
		public static String Vendorbillno;
		public static String Gidno;
		public static String StyleCode;
		public static String Origion;
		public static String Baseuomcode;
		public static String Baseuomdescription;
		public static String Vendorno;
		public static String Reason;
		public static String Dicountcode;
		public static String Type;
		public static String Zonecode;
		public static String ZoneName;
		public static String PoNo;
		public static String CompanyCode;
		public static String CompanyName;
		public static String Amount;
		public static String PaymentDate;
		public static String Refno;
		public static String RefDate;
		public static String AdjtypeCode;
		public static String AdjtypeName;
		public static String MerchandiseCode;
		public static String Summary;
		public static String Proceed;
		public static String NewVendornum;
		public static String Status;
		public static String ManufacturerCode;
		public static String ManufacturerName;
		public static String Email;
		public static String MinMax;
		public static String Bulkchild;
		public static String Presupplywise;
		public static String Basedoninventory;
		public static String Soldqty;
		public static String Reorderbynoofdays;
		public static String Soldqtyinlastpurchase;
		public static String Reqtycycledays;
		public static String Barcode;
		public static String LocationCode1;
		public static String LocationCode2;
		public static String Price;
		public static String Batch3;
		public static String Selectfield;
		public static String Changefield;
		public static String OrigionCode;
		public static String Transportname;
		public static String Person;
		public static String URL;
		public static String Batch4;
		public static String Batch5;
		public static String Dateformat;
		public static String Template;
		public static String Printername;
		public static String result;
		public static String MinQty;
		public static String MaxQty;
		public static String ReorderQty;
		public static String Cycledays;
		public static String Orderby;
		public static String CheckBox1;
		public static String CheckBox2;
		public static String Expireddate;
		public static String SerialnoEntry;
		public static String AutoPO;
		public static String Packageitem;
		public static String Loyality;
		public static String Special;
		public static String ShelfStorage;
		public static String HideDataOnBarcode;
		public static String Markingitem;
		public static String NeedBarcodePrint;
		public static String AllowCostEditinGRN;
		public static String Weightbased;
		public static String PurchaseOrder;
		public static String GRNPurchase;
		public static String PointOfSale;
		public static String AllowNegative;
		public static String TransferDC;
		public static String EligibilityQty;
		public static String SalesReturn;
		public static String OrderBooking;
		public static String Estimation;
		public static String Quatation;
		public static String OnlineOrder;
		public static String Purchasereturn;
		public static String inventorysearch;
		public static String Chequeno;
		public static String City;
		public static String NoOfRecords;
		public static String Paymode;
		public static String Issued;
		public static String UnIssued;
		public static String All;
		public static String CreditLimit;
		public static String CreditDays;
		public static String HoldInv;
		public static String AllInv;
		public static String BankCode;
		public static String Paymode1;
		public static String BankCode1;
		public static String ChequeNo;
		public static String Invoiceno;
		public static String Customername;
		public static String ChequeDate;
		public static String Cashier;
		public static String Terminal;
		public static String CustomerCode;
		public static String MinAmt;
		public static String MaxAmt;
		public static String CashSales;
		public static String CreditSales;
		public static String CancelBill;
		public static String ExchangeBill;
		public static String DiscountBill;
		public static String SalesReturnBill;
		public static String Path;
		public static String Filter;
		public static String Vehicle;
		public static String GidNo;
		public static String LQty;
		public static String FromLocationStatus;
		public static String ToLocationStatus;
		public static String FromLocation;
		public static String ToLocation;
		public static String TransferNo;
		public static String Company;
		public static String BranchCode;
		public static String Name;
		public static String Country;
		public static String State;
		public static String PostalCode;
		public static String WebPage;
		public static String DateFormat;
		public static String Time;
		public static String DefaultCurrency;
		public static String CurencySign;
		public static String BusinessRegNo;
		public static String TaxType;
		public static String Percentage;
		public static String GSTTIN;
		public static String BillMessage1;
		public static String BillMessage2;
		public static String DisplayMessage1;
		public static String DisplayMessage2;
		public static String NextMailID;
		public static String NextBankTransNo;
		public static String DLNo;
		public static String Location;
		public static String SortCode;
		public static String WareHousecode;
		public static String ReasonCode;
		public static String ReasonDescription;
		public static String TransactionType;
		public static String AdditionOrDeduction;
		public static String SystemName;
		public static String Floor;
		public static String PosScreenType;
		public static String TillType;
		public static String TillCode;
		public static String TillDesc;
		public static String IsPharmacyter;
		public static String ItemDelAllowed;
		public static String SpecialCounter;
		public static String OpticalTerminal;
		public static String AutoLoginPos;
		public static String NegStock;
		public static String PriceChangeAllowed;
		public static String AllowDisCoupon;
		public static String AmazonPayMin;
		public static String AmazonPayMax;
		public static String CardsMin;
		public static String CardsMax;
		public static String CashMin;
		public static String CashMax;
		public static String ChequeMin;
		public static String ChequeMax;
		public static String CreditMin;
		public static String CreditMax;
		public static String CreditNoteMin;
		public static String CreditNoteMax;
		public static String DueMin;
		public static String DueMax;
		public static String FCouponsMin;
		public static String FCouponsMax;
		public static String FcurrencyMin;
		public static String FcurrencyMax;
		public static String GpayMin;
		public static String GpayMax;
		public static String GVmin;
		public static String GvMax;
		public static String LoyaltyMin;
		public static String LoyaltyMax;
		public static String OthersMin;
		public static String OthersMax;
		public static String PaytmMin;
		public static String PaytmMax;
		public static String PaytmsMin;
		public static String PaytmsMax;
		public static String Phonepemin;
		public static String Phonepemax;
		public static String SOadvmin;
		public static String SOadvMax;
		public static String SOdexoMin;
		public static String SOdexoMax;
		public static String UnPaidMin;
		public static String UnPaidMax;
		public static String WalletMin;
		public static String WalletMax;
		public static String Tender0;
		public static String Refund0;
		public static String Allow;
		public static String IsPrePrint;
		public static String Template0;
		public static String print;
		public static String PrinterAttached;
		public static String LocDeviceName;
		public static String BarcodePrinter;
		public static String PoleDisAttached;
		public static String Port;
		public static String PoleDisLogName;
		public static String CashDrawerAttached;
		public static String CashDrawerLogDisName;
		public static String WeighingMachineAttached;
		public static String SystemPort;
		public static String SystemAllow;
		public static String BBill;
		public static String CashBill;
		public static String CreditBill;
		public static String CustomerAdvance;
		public static String CustomerReceivable;
		public static String DeliveryChallan;
		public static String DeliverySheet;
		public static String GiftVoucher;
		public static String InterCompanySales;
		public static String Payment;
		public static String PreBill;
		public static String Receipt;
		public static String Refund;
		public static String SalesOrder;
		public static String SalesReturnRequest;
		public static String ServiceBill;
		public static String Settlement;
		public static String StaffSales;
		public static String TradeIn;
		public static String VendorOrder;
		
		public static String Title;
		public static String CustomerName;
		public static String IdType;
		public static String DOB;
		public static String Occupation;
		public static String Designation;
		public static String Employer;
		public static String IdNo;
		public static String AgeGroup;
		public static String MaritalStatus;
		public static String Education;
		public static String Income;
		public static String MemberType;
		public static String Representative;
		public static String Gender;
		public static String AnniversaryStatus;
		public static String Address3;
		public static String Distance;
		public static String Pin;
		public static String Nationality;
		public static String Area;
		public static String Zone;
		public static String MobileNo;
		public static String PhoneO;
		public static String OtherDeatails;
		public static String LoyaltyCard;
		public static String CreditType;
		public static String AllowDiscount;
		public static String TermsCode;
		public static String Value;
		public static String DisplayCode;
		public static String DisplayName;
		public static String DisplayChargesPerday;
		public static String DisplayChargesPermonth;
		public static String PersonInCharge;
		public static String Cloth;
		public static String Color;
		public static String Design;
		public static String Fit;
		public static String Neck;
		public static String Sleeve;
		public static String Active;
		public static String BankName;
		public static String SalesManID;
		public static String EmployeeCode;
		public static String SalesManName;
		public static String Commission;
		public static String DeliveryManId;
		public static String DeliveryMan;
	    public static String Cost;
	    public static String PaymentCode;
	    public static String PaymentDesc;
	    public static String Position;
	    public static String ServiceCharge;
	    public static String GlAccountCode;
	    public static String Denamination;
	    public static String Vehiclemastercode;
	    public static String DriverName;
	    public static String BagCode;
	    public static String PrinterCode;
		public static String PickerMasterId;
		public static String PickerMasterName ;
		public static String PickerStatus;
		public static String ParamCode;
		public static String CreatedBy;
		public static String CST;
		
		public static String ZipCode;
		public static String PhoneNo;
		public static String PurchaseLimit;
		public static String Attn;
		public static String PurchaseProfit;
		public static String SellingMargin;
		public static String PORemarks;
		public static String ChequePrintName;
		public static String BankACNo;
		public static String IFSCCode;
		public static String HoldBills;
		public static String HoldBill;
		public static String CrLimit;
		public static String CRLIMIT;
		public static String CrDays;
		public static String StopPayment;
		public static String StopPurchase;
		public static String StopReason;
		public static String Sunday;
		public static String Monday;
		public static String Tuesday;
		public static String Wednesday;
		public static String Thursday;
	    public static String Friday;
	    public static String Saturday;
	    public static String Customer;
	    public static String SalesMan;
	    public static String BatchNo;
	    public static String Batch6;
	    public static String Batch7;
	    public static String Batch8;
	    public static String Batch9;
	    public static String Batch10;
	    public static String Batch11;
	    
	    public static String Batch12;
	    public static String Batch13;
	    public static String Batch14;
	    public static String Batch15;
	    public static String Batch16;
	    public static String Batch17;
	    public static String Batch18;
	    public static String Batch19;
	    public static String Batch20;
	    public static String Batch21;
	    public static String Batch22;
	    public static String Batch23;
	    public static String Batch24;
	    public static String Batch25;
	    public static String Batch26;
	    public static String Tax;
	    public static String User;
	    public static String Batch27;
	    public static String Batch28;
	    public static String Batch29;
	    public static String Batch30;
		
		
		
		
		
		

	
		
		
		
	}
	
	

}
